//prettier-ignore
export const movieList = [
    {
        id: "movie1",
        name: "Rising Arizona",
        releaseYear: "1987",
        runtime: "1h34m",
        summary:"When a childless couple of an ex-con and an ex-cop decide to help themselves to one of another family's quintuplets, their lives become more complicated than they anticipated.",
        director: ["Joel Coen", "Ethan Coen"],
        writers: ["Joel Coen", "Ethan Coen"],
        actors: ["Nicolas Cage","Holly Hunter","Trey Wilson","John Goodman","William Forsythe","Sam McMurray","Frances McDormand",],
        genre: ["comedy", "crime"],
        poster: "https://m.media-amazon.com/images/M/MV5BOGUwZTEwZTYtZmQ0OS00NmM1LWE2ZTQtNjZiYmE4ZmUxMjk1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
        links: ["https://www.imdb.com/title/tt0093822/", "https://www.rottentomatoes.com/m/raising_arizona"],
    },
    {
        id: "movie2",
        name: "Troy",
        releaseYear: "2004",
        runtime: "2h 43m",
        summary:"An adaptation of Homer's great epic, the film follows the assault on Troy by the united Greek forces and chronicles the fates of the men involved.",
        director: ["Wolfgang Petersen"],
        writers: ["Homer", "David Benioff"],
        actors: ["Brad Pitt", "Eric Bana", "Orlando Bloom", "Julian Glover", "Brian Cox", "Nathan Jones", "Adoni Maropis", "Diane Kruger", "Sean Bean", "Garrett Hedlund"],
        genre: ["Drama", "History"],
        poster: "https://www.google.com/search?q=troy&rlz=1C1GCEA_enRS982RS982&sxsrf=AOaemvJGluvsC-l10Bj3UVXBr3A5P_HsKw:1638539325849&tbm=isch&source=iu&ictx=1&fir=L467Cuw1gJr5KM%252CMuimAWKOrdxauM%252C%252Fm%252F01vw8k%253B2EcXFHHwnC0jjM%252CerWJWK99oe78fM%252C_%253BQfTCrxDxu-8pRM%252C48HO_ko48qGUpM%252C_%253BQD_gx5jDkh2rJM%252CC5aCWaXdPRsQCM%252C_%253BGfWVY29oJrrERM%252CQbhuRH9LHqJPFM%252C_%253B0TwwHP9O1hfJeM%252CecQ2xOnISafubM%252C_%253B1P6Ga4qM-eMg-M%252C3wtzHnscBIvSgM%252C_%253BxkUmfJ8u_yiBPM%252CeNJzDIZ4rpMiNM%252C_&vet=1&usg=AI4_-kTp2oPEiYYLjSHBZvZlG0X4s59i3w&sa=X&ved=2ahUKEwirp97T4sf0AhX1g_0HHWkeCo8Q_B16BAhgEAE#imgrc=2EcXFHHwnC0jjM",
        links: ["https://www.imdb.com/title/tt0332452/", "https://www.rottentomatoes.com/m/troy"],
    },
    {
        id: "movie3",
        name: "The Big Lebowski",
        releaseYear: "1998",
        runtime: "1h 57m",
        summary:"Ultimate L.A. slacker Jeff 'The Dude' Lebowski, mistaken for a millionaire of the same name, seeks restitution for a rug ruined by debt collectors, enlisting his bowling buddies for help while trying to find the millionaire's missing wife.",
        director: ["Joel Coen", "Ethan Coen"],
        writers:["Joel Coen", "Ethan Coen"],
        actors: ["Jeff Bridges", "John Goodman", "Steve Buscemi", "Julianne Moor", "David Huddleston", "Philip Seymour Hoffman"],
        genre: ["Comedy", "Crime", "Sport"],
        links: {
            imdb: "https://www.imdb.com/title/tt0118715/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/the_big_lebowski",
            poster: "https://m.media-amazon.com/images/M/MV5BMTQ0NjUzMDMyOF5BMl5BanBnXkFtZTgwODA1OTU0MDE@._V1_.jpg"
        },
    },
    {
        id: "movie4",
        name: "O Brother, Where Art Thou?",
        releaseYear: "2000",
        runtime: "1h 47m",
        summary:"In the deep south during the 1930s, three escaped convicts search for hidden treasure while a relentless lawman pursues them.",
        director: ["Joel Coen", "Ethan Coen"],
        writers:["Joel Coen", "Ethan Coen"],
        actors: ["George Clooney", "John Turturro", "Tim Blake Nelson", "John Goodman", "Holly Hunter", "Chris Thomas King", "Charles Durning"],
        genre: ["Adventure", "Comedy", "Crime"],
        links: {
            imdb: "https://www.imdb.com/title/tt0190590/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/o_brother_where_art_thou",
            poster: "https://www.google.com/search?q=O+Brother,+Where+Art+Thou%3F&rlz=1C1GCEA_enRS982RS982&sxsrf=AOaemvICgVAf1_jdV9N9e5yNdgDK1Par9Q:1638540261047&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjVmNaR5sf0AhWY57sIHSxdBWgQ_AUoAXoECAEQAw#imgrc=rRDEZnq00gjAyM"
        },
    },
    {
        id: "movie5",
        name: "Call Me by Your Name",
        releaseYear: "2017",
        runtime: "2h 12m",
        summary:"In 1980s Italy, romance blossoms between a seventeen-year-old student and the older man hired as his father's research assistant.",
        director: ["Luca Guadagnino"],
        writers:["James Ivory", "André Aciman"],
        actors: ["Armie Hammer", "Timothée Chalamet", "Michael Stuhlbarg", "Amira Casar", "Eshter Garrel"],
        genre: [],
        links: {
            imdb: "https://www.imdb.com/title/tt5726616/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/call_me_by_your_name",
            poster: "https://m.media-amazon.com/images/M/MV5BNDk3NTEwNjc0MV5BMl5BanBnXkFtZTgwNzYxNTMwMzI@._V1_.jpg"
        },
    },
    {
        id: "movie6",
        name: "SPACE SWEEPERS",
        releaseYear: "2021",
        runtime: "2h 16m",
        summary:"Set in the year 2092 and follows the crew of a space junk collector ship called The Victory. When they discover a humanoid robot named Dorothy that's known to be a weapon of mass destruction, they get involved in a risky business deal.",
        director: ["Sung-hee Jo"],
        writers:["Sung-hee Jo"],
        actors: ["Song Joong-ki", "Kim Tae-ri", "Jin Seon-kyu", "Hae-Jin Yoo", "Richard Armitage"],
        genre: ["Action", "Adventure", "Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt12838766/?ref_=ttfc_fc_tt",
            rottenTomatoes: "https://www.rottentomatoes.com/m/space_sweepers",
            poster: "https://m.media-amazon.com/images/M/MV5BZTUxN2M3ZWYtMzc1MC00NTc4LWFhZDItMzViZDg2NmFjMzBhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg"
        },
    },
    {
        id: "movie7",
        name: "Nomadland",
        releaseYear: "2000",
        runtime: "1h 47m",
        summary:"A woman in her sixties, after losing everything in the Great Recession, embarks on a journey through the American West, living as a van-dwelling modern-day nomad.",
        director: ["Chloé Zhao"],
        writers:["Chloé Zhao", "Jessica Bruder"],
        actors: ["Frances McDormand", "David Strathairn", "Linda May", "Gay DeForest", "Patricia Grier", "Angela Reyes", "Carl R. Hughes", "Douglas G. Soul"],
        genre: ["Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt9770150/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/nomadland",
            poster: "https://m.media-amazon.com/images/M/MV5BMDRiZWUxNmItNDU5Yy00ODNmLTk0M2ItZjQzZTA5OTJkZjkyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"
        },
    },
    {
        id: "movie8",
        name: "Akira",
        releaseYear: "1988",
        runtime: "2h 4m",
        summary:"A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath who can only be stopped by a teenager, his gang of biker friends and a group of psychics.",
        director: ["Katsuhiro Ôtomo"],
        writers:["Katsuhiro Ôtomo", "Izô Hashimoto"],
        actors: ["Mitsuo Iwata", "Nozomu Sasaki", "Mami Koyama", "Tesshô Genda"],
        genre: ["Animation", "Action", "Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt0094625/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/akira",
            poster: "https://m.media-amazon.com/images/M/MV5BM2ZiZTk1ODgtMTZkNS00NTYxLWIxZTUtNWExZGYwZTRjODViXkEyXkFqcGdeQXVyMTE2MzA3MDM@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie9",
        name: "The Bourne Identity",
        releaseYear: "2002",
        runtime: "1h 59m",
        summary:"A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and attempting to regain his memory.",
        director: ["Doug Liman"],
        writers:["Tony Gilroy", "W. Blake Heron", "Robert Ludlum"],
        actors: ["Matt Damon", "Franka Potente", "Chris Cooper", "Clive Owen", "Brian Cox", "Julia Stiles"],
        genre: ["Action", "Mystery", "Thriller"],
        links: {
            imdb: "",
            rottenTomatoes: "https://www.rottentomatoes.com/m/bourne_identity",
            poster: "https://m.media-amazon.com/images/M/MV5BM2JkNGU0ZGMtZjVjNS00NjgyLWEyOWYtZmRmZGQyN2IxZjA2XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg"
        },
    },
    {
        id: "movie10",
        name: "Monster Hunter",
        releaseYear: "2020",
        runtime: "1h 43m",
        summary:"When Cpt. Artemis and her loyal soldiers are transported to a new world, they engage in a desperate battle for survival against enormous enemies with incredible powers. Feature film based on the video game by Capcom.",
        director: ["Paul W.S. Anderson"],
        writers:["Paul W.S Anderson", "kaname Fujioka"],
        actors: ["Milla Jovovich", "Tony Jaa", "Ron Perlman", "T.I", "Diego Boneta", "Meagan Good", "Lathalos"],
        genre: ["Action", "Adventure", "Fantasy"],
        links: {
            imdb: "https://www.imdb.com/title/tt6475714/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/monster_hunter",
            poster: "https://m.media-amazon.com/images/M/MV5BOGU3NTFmNjYtODc3Ny00MWEzLWI3M2ItZjE3NDgwMTI0MzkzXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg"
        },
    },
    {
        id: "movie11",
        name: "The Bourne Supremacy",
        releaseYear: "2004",
        runtime: "1h 48m",
        summary:"When Jason Bourne is framed for a CIA operation gone awry, he is forced to resume his former life as a trained assassin to survive.",
        director: ["Paul GreenGrass"],
        writers:["Robert Ludlum", "Tony Gilroy"],
        actors: ["Matt Damon", "Franka Potente", "Joan Allen", "Brian Cox", "Julia Stiles", "Karl Urban"],
        genre: ["Action", "Mystery", "Thriller"],
        links: {
            imdb: "https://www.imdb.com/title/tt0372183/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/bourne_supremacy",
            poster: "https://m.media-amazon.com/images/M/MV5BYTIyMDFmMmItMWQzYy00MjBiLTg2M2UtM2JiNDRhOWE4NjBhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg"
        },
    },
    {
        id: "movie12",
        name: "Wolfwalkers",
        releaseYear: "2020",
        runtime: "1h 43m",
        summary:"A young apprentice hunter and her father journey to Ireland to help wipe out the last wolf pack. But everything changes when she befriends a free-spirited girl from a mysterious tribe rumored to transform into wolves by night.",
        director: ["Tomm Moore", "Ross Stewart"],
        writers:["Will Collins", "Tomm Moore", "Ross Stewart"],
        actors: ["Honor Kneafsey", "Eva Whittaker", "Sean Bean", "Simon McBurney", "Tommy Tiernan", "Maria Doyle Kennedy"],
        genre: ["Animation", "Adventure", "Family"],
        links: {
            imdb: "https://www.imdb.com/title/tt5198068/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/wolfwalkers",
            poster: "https://m.media-amazon.com/images/M/MV5BNTA4MWQ4NGUtOGQ0MS00M2QyLWE5MDItZWM2YzA0ZDgxZTA2XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_.jpg"
        },
    },
    {
        id: "movie13",
        name: "Justice League",
        releaseYear: "2017",
        runtime: "2h",
        summary:"Fueled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne enlists the help of his new-found ally, Diana Prince, to face an even greater enemy.",
        director: ["Zack Snyder"],
        writers:["Jerry Siegel", "joe Shuster", "Chris Terrio"],
        actors: ["ben Affleck", "Gal Gadot", "Jason Momoa", "Ezra Miller", "Henry Cavill", "Amy Adams", "Ray Fisher", "Jeremy Irons", "Diane Lane", "Connie Nielsen", "J.K Simmons"],
        genre: ["Action", "Adventure", "Fantasy", "Comic Book"],
        links: {
            imdb: "https://www.imdb.com/title/tt0974015/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/zack_snyders_justice_league",
            poster: "https://images-na.ssl-images-amazon.com/images/I/81KX513BQxL.jpg"
        },
    },
    {
        id: "movie14",
        name: "Moonlight",
        releaseYear: "2016",
        runtime: "1h 51m",
        summary: "A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood",
        director: ["Barry Jenkins"],
        writers:["Barry Jenkins", "Tarell Alvin McCraney"],
        actors: ["Mahershala Ali", "Naomie Harris", "Trevante Rhodes", "Alex R. Hibbert", "Shariff Earp", "Duan Sanderson", "Janelle Monáe", "Jaden Piner"],
        genre: ["Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt4975722/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/moonlight_2016",
            poster: "https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie2",
        name: "",
        releaseYear: "",
        runtime: "",
        summary:"",
        director: [],
        writers:[],
        actors: [],
        genre: [],
        links: {
            imdb: "",
            rottenTomatoes: "",
            poster: ""
        },
    },
    {
        id: "movie2",
        name: "",
        releaseYear: "",
        runtime: "",
        summary:"",
        director: [],
        writers:[],
        actors: [],
        genre: [],
        links: {
            imdb: "",
            rottenTomatoes: "",
            poster: ""
        },
    },

    
];
